/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  NorthStarForm,
  PostApiGoalDeleteParams
} from '../../models';



  type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type getApiGoalGetResponse200 = {
  data: void
  status: 200
}

export type getApiGoalGetResponseSuccess = (getApiGoalGetResponse200) & {
  headers: Headers;
};
;

export type getApiGoalGetResponse = (getApiGoalGetResponseSuccess)

export const getGetApiGoalGetUrl = () => {




  return `/api/Goal/Get`
}

export const getApiGoalGet = async ( options?: RequestInit): Promise<getApiGoalGetResponse> => {

  const res = await fetch(getGetApiGoalGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiGoalGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiGoalGetResponse
}




export const getGetApiGoalGetKey = () => [`/api/Goal/Get`] as const;

export type GetApiGoalGetQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGoalGet>>>

export const useGetApiGoalGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiGoalGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiGoalGetKey() : null);
  const swrFn = () => getApiGoalGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiGoalCreateNorthStarResponse200 = {
  data: void
  status: 200
}

export type postApiGoalCreateNorthStarResponseSuccess = (postApiGoalCreateNorthStarResponse200) & {
  headers: Headers;
};
;

export type postApiGoalCreateNorthStarResponse = (postApiGoalCreateNorthStarResponseSuccess)

export const getPostApiGoalCreateNorthStarUrl = () => {




  return `/api/Goal/CreateNorthStar`
}

export const postApiGoalCreateNorthStar = async (northStarForm: NorthStarForm, options?: RequestInit): Promise<postApiGoalCreateNorthStarResponse> => {

  const res = await fetch(getPostApiGoalCreateNorthStarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      northStarForm,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiGoalCreateNorthStarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiGoalCreateNorthStarResponse
}




export const getPostApiGoalCreateNorthStarMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: NorthStarForm }) => {
    return postApiGoalCreateNorthStar(arg, options);
  }
}
export const getPostApiGoalCreateNorthStarMutationKey = () => [`/api/Goal/CreateNorthStar`] as const;

export type PostApiGoalCreateNorthStarMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGoalCreateNorthStar>>>

export const usePostApiGoalCreateNorthStar = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiGoalCreateNorthStar>>, TError, Key, NorthStarForm, Awaited<ReturnType<typeof postApiGoalCreateNorthStar>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiGoalCreateNorthStarMutationKey();
  const swrFn = getPostApiGoalCreateNorthStarMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiGoalDeleteResponse200 = {
  data: void
  status: 200
}

export type postApiGoalDeleteResponseSuccess = (postApiGoalDeleteResponse200) & {
  headers: Headers;
};
;

export type postApiGoalDeleteResponse = (postApiGoalDeleteResponseSuccess)

export const getPostApiGoalDeleteUrl = (params?: PostApiGoalDeleteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Goal/Delete?${stringifiedParams}` : `/api/Goal/Delete`
}

export const postApiGoalDelete = async (params?: PostApiGoalDeleteParams, options?: RequestInit): Promise<postApiGoalDeleteResponse> => {

  const res = await fetch(getPostApiGoalDeleteUrl(params),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiGoalDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiGoalDeleteResponse
}




export const getPostApiGoalDeleteMutationFetcher = (params?: PostApiGoalDeleteParams, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiGoalDelete(params, options);
  }
}
export const getPostApiGoalDeleteMutationKey = (params?: PostApiGoalDeleteParams,) => [`/api/Goal/Delete`, ...(params ? [params]: [])] as const;

export type PostApiGoalDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGoalDelete>>>

export const usePostApiGoalDelete = <TError = Promise<unknown>>(
  params?: PostApiGoalDeleteParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiGoalDelete>>, TError, Key, Arguments, Awaited<ReturnType<typeof postApiGoalDelete>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiGoalDeleteMutationKey(params);
  const swrFn = getPostApiGoalDeleteMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
