/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const GetApiGoalGetResponseItem = zod.object({
  "description": zod.string().optional(),
  "importance": zod.number().optional(),
  "justification": zod.string().optional(),
  "bearings": zod.array(zod.object({
  "parentId": zod.string().uuid().optional(),
  "description": zod.string().optional(),
  "justification": zod.string().optional(),
  "strengths": zod.string().nullish(),
  "weaknesses": zod.string().nullish(),
  "movements": zod.array(zod.object({
  "parentId": zod.string().uuid().optional(),
  "motivationType": zod.union([zod.null(),zod.number()]).optional(),
  "motivation": zod.string().nullish(),
  "triggers": zod.string().nullish(),
  "temptations": zod.string().nullish(),
  "opts": zod.string().nullish(),
  "obstacles": zod.string().nullish(),
  "killConditions": zod.string().nullish(),
  "id": zod.string().uuid().optional(),
  "name": zod.string().optional()
})).optional(),
  "id": zod.string().uuid().optional(),
  "name": zod.string().optional()
})).optional(),
  "id": zod.string().uuid().optional(),
  "name": zod.string().optional()
})
export const GetApiGoalGetResponse = zod.array(GetApiGoalGetResponseItem)

export const PostApiGoalCreateNorthStarBody = zod.object({
  "description": zod.string(),
  "importance": zod.number(),
  "justification": zod.string().optional(),
  "name": zod.string(),
  "type": zod.number().optional()
})

export const PostApiGoalCreateBearingBody = zod.object({
  "parentId": zod.string().uuid(),
  "description": zod.string().optional(),
  "justification": zod.string().optional(),
  "strengths": zod.string().nullish(),
  "weaknesses": zod.string().nullish(),
  "name": zod.string(),
  "type": zod.number().optional()
})

export const PostApiGoalCreateMovementBody = zod.object({
  "parentId": zod.string().uuid(),
  "motivationType": zod.union([zod.null(),zod.number()]).optional(),
  "motivation": zod.string().nullish(),
  "triggers": zod.string().nullish(),
  "temptations": zod.string().nullish(),
  "opts": zod.string().nullish(),
  "obstacles": zod.string().nullish(),
  "killConditions": zod.string().nullish(),
  "name": zod.string(),
  "type": zod.number().optional()
})

export const PostApiGoalDeleteQueryParams = zod.object({
  "ID": zod.string().optional()
})

