/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getApiEventGetResponseOneTitleMax = 200;

export const getApiEventGetResponseTwoTitleMax = 200;



export const GetApiEventGetResponseItem = zod.union([zod.object({
  "type": zod.enum(['onetime']),
  "id": zod.string().uuid(),
  "movementId": zod.string().uuid().nullable(),
  "title": zod.string().max(getApiEventGetResponseOneTitleMax),
  "start": zod.string().datetime({"offset":true}),
  "end": zod.string().datetime({"offset":true})
}),zod.object({
  "type": zod.enum(['recurring']),
  "recurrence": zod.object({
  "rrule": zod.string(),
  "exDate": zod.array(zod.string())
}),
  "id": zod.string().uuid(),
  "movementId": zod.string().uuid().nullable(),
  "title": zod.string().max(getApiEventGetResponseTwoTitleMax),
  "start": zod.string().datetime({"offset":true}),
  "end": zod.string().datetime({"offset":true})
})])
export const GetApiEventGetResponse = zod.array(GetApiEventGetResponseItem)

export const postApiEventCreateOnetimeBodyNameMax = 200;

export const postApiEventCreateOnetimeBodyDurationRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const PostApiEventCreateOnetimeBody = zod.object({
  "movementId": zod.string().uuid().nullable(),
  "name": zod.string().max(postApiEventCreateOnetimeBodyNameMax),
  "start": zod.string().datetime({"offset":true}),
  "duration": zod.union([zod.number(),zod.string().regex(postApiEventCreateOnetimeBodyDurationRegExpTwo)])
})

export const PostApiEventCreateOnetimeResponse = zod.string().uuid()

export const postApiEventCreateRecurringBodyRecurrenceAmountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const postApiEventCreateRecurringBodyMonthDayRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const postApiEventCreateRecurringBodyYearMonthRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const postApiEventCreateRecurringBodyNameMax = 200;

export const postApiEventCreateRecurringBodyDurationRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const PostApiEventCreateRecurringBody = zod.object({
  "recurrenceAmount": zod.union([zod.number(),zod.string().regex(postApiEventCreateRecurringBodyRecurrenceAmountRegExpTwo)]),
  "recurrenceType": zod.number(),
  "weekDays": zod.array(zod.number()),
  "monthDay": zod.union([zod.number(),zod.string().regex(postApiEventCreateRecurringBodyMonthDayRegExpTwo)]),
  "yearMonth": zod.union([zod.number(),zod.string().regex(postApiEventCreateRecurringBodyYearMonthRegExpTwo)]),
  "movementId": zod.string().uuid().nullable(),
  "name": zod.string().max(postApiEventCreateRecurringBodyNameMax),
  "start": zod.string().datetime({"offset":true}),
  "duration": zod.union([zod.number(),zod.string().regex(postApiEventCreateRecurringBodyDurationRegExpTwo)])
})

export const PostApiEventCreateRecurringResponse = zod.string().uuid()

