/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getApiEventGetResponseOneTitleMax = 200;

export const getApiEventGetResponseTwoTitleMax = 200;



export const GetApiEventGetResponseItem = zod.union([zod.object({
  "type": zod.enum(['onetime']),
  "id": zod.string().uuid(),
  "movementId": zod.string().uuid().nullish(),
  "title": zod.string().max(getApiEventGetResponseOneTitleMax),
  "start": zod.string().datetime({"offset":true}),
  "end": zod.string().datetime({"offset":true})
}),zod.object({
  "type": zod.enum(['recurring']),
  "recurrence": zod.object({
  "rrule": zod.string(),
  "exDate": zod.array(zod.string())
}),
  "id": zod.string().uuid(),
  "movementId": zod.string().uuid().nullish(),
  "title": zod.string().max(getApiEventGetResponseTwoTitleMax),
  "start": zod.string().datetime({"offset":true}),
  "end": zod.string().datetime({"offset":true})
})])
export const GetApiEventGetResponse = zod.array(GetApiEventGetResponseItem)

export const postApiEventCreateOnetimeBodyNameMax = 200;

export const postApiEventCreateOnetimeBodyDurationRegExp = new RegExp('^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$');


export const PostApiEventCreateOnetimeBody = zod.object({
  "movementId": zod.string().uuid().nullish(),
  "name": zod.string().max(postApiEventCreateOnetimeBodyNameMax),
  "startDate": zod.string().date(),
  "startTime": zod.string().time({}),
  "duration": zod.string().regex(postApiEventCreateOnetimeBodyDurationRegExp)
})

export const PostApiEventCreateOnetimeResponse = zod.string().uuid()

export const postApiEventCreateRecurringBodyRecurrenceAmountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const postApiEventCreateRecurringBodyMonthDayMaxOne = 31;

export const postApiEventCreateRecurringBodyMonthDayMaxTwo = 31;


export const postApiEventCreateRecurringBodyMonthDayRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const postApiEventCreateRecurringBodyYearMonthMaxOne = 12;

export const postApiEventCreateRecurringBodyYearMonthMaxTwo = 12;


export const postApiEventCreateRecurringBodyYearMonthRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const postApiEventCreateRecurringBodyNameMax = 200;

export const postApiEventCreateRecurringBodyDurationRegExp = new RegExp('^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$');


export const PostApiEventCreateRecurringBody = zod.object({
  "recurrenceAmount": zod.union([zod.number(),zod.string().regex(postApiEventCreateRecurringBodyRecurrenceAmountRegExpTwo)]),
  "recurrenceType": zod.enum(['DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY']),
  "weekDays": zod.array(zod.enum(['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'])).nullish(),
  "monthDay": zod.union([zod.number().min(1).max(postApiEventCreateRecurringBodyMonthDayMaxOne),zod.string().min(1).max(postApiEventCreateRecurringBodyMonthDayMaxTwo).regex(postApiEventCreateRecurringBodyMonthDayRegExpTwo)]).nullish(),
  "yearMonth": zod.union([zod.number().min(1).max(postApiEventCreateRecurringBodyYearMonthMaxOne),zod.string().min(1).max(postApiEventCreateRecurringBodyYearMonthMaxTwo).regex(postApiEventCreateRecurringBodyYearMonthRegExpTwo)]).nullish(),
  "movementId": zod.string().uuid().nullish(),
  "name": zod.string().max(postApiEventCreateRecurringBodyNameMax),
  "startDate": zod.string().date(),
  "startTime": zod.string().time({}),
  "duration": zod.string().regex(postApiEventCreateRecurringBodyDurationRegExp)
})

export const PostApiEventCreateRecurringResponse = zod.string().uuid()

