/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GoalType } from './goalType';

export interface BearingCreate {
  description?: string;
  justification?: string;
  /** @nullable */
  strengths?: string | null;
  /** @nullable */
  weaknesses?: string | null;
  parentId?: string;
  name: string;
  type?: GoalType;
}
