/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MovementGet } from './movementGet';

export interface BearingGet {
  parentId?: string;
  description?: string;
  justification?: string;
  /** @nullable */
  strengths?: string | null;
  /** @nullable */
  weaknesses?: string | null;
  movements?: MovementGet[];
  id?: string;
}
