/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Movement } from './movement';
import type { NorthStar } from './northStar';
import type { User } from './user';

export interface Bearing {
  northStarId?: string;
  northStar?: NorthStar;
  /** @maxLength 5000 */
  description?: string;
  /** @maxLength 5000 */
  justification?: string;
  /**
     * @maxLength 5000
     * @nullable
     */
  strengths?: string | null;
  /**
     * @maxLength 5000
     * @nullable
     */
  weaknesses?: string | null;
  movements?: Movement[];
  id?: string;
  userId?: string;
  user?: User;
  /** @maxLength 200 */
  name: string;
}
