/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Movement } from './movement';
import type { User } from './user';

export interface Event {
  id?: string;
  userId?: string;
  user?: User;
  /** @nullable */
  movementId?: string | null;
  movement?: null | Movement;
  /** @maxLength 200 */
  name?: string;
  start?: string;
  end?: string;
}
