/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GoalType } from './goalType';
import type { User } from './user';

export interface Goal {
  id?: string;
  user?: User;
  name?: string;
  goalType?: GoalType;
}
