/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Bearing } from './bearing';
import type { MotivationType } from './motivationType';
import type { User } from './user';

export interface Movement {
  bearingId?: string;
  bearing?: Bearing;
  /**
     * @maxLength 5000
     * @nullable
     */
  difficulty?: string | null;
  motivationType?: null | MotivationType;
  /**
     * @maxLength 5000
     * @nullable
     */
  motivation?: string | null;
  /**
     * @maxLength 5000
     * @nullable
     */
  triggers?: string | null;
  /**
     * @maxLength 5000
     * @nullable
     */
  temptations?: string | null;
  /**
     * @maxLength 5000
     * @nullable
     */
  obstacles?: string | null;
  /**
     * @maxLength 5000
     * @nullable
     */
  killConditions?: string | null;
  id?: string;
  userId?: string;
  user?: User;
  /** @maxLength 200 */
  name: string;
}
