/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GoalType } from './goalType';
import type { MotivationType } from './motivationType';

export interface MovementCreate {
  bearingId?: string;
  motivationType?: null | MotivationType;
  /** @nullable */
  motivation?: string | null;
  /** @nullable */
  triggers?: string | null;
  /** @nullable */
  temptations?: string | null;
  /** @nullable */
  opts?: string | null;
  /** @nullable */
  obstacles?: string | null;
  /** @nullable */
  killConditions?: string | null;
  name: string;
  type?: GoalType;
}
