/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MotivationType } from './motivationType';

export interface MovementGet {
  bearingId?: string;
  motivationType?: null | MotivationType;
  /** @nullable */
  motivation?: string | null;
  /** @nullable */
  triggers?: string | null;
  /** @nullable */
  temptations?: string | null;
  /** @nullable */
  obstacles?: string | null;
  /** @nullable */
  killConditions?: string | null;
  id?: string;
  name?: string;
}
