/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Bearing } from './bearing';
import type { GoalImportance } from './goalImportance';
import type { User } from './user';

export interface NorthStar {
  /** @maxLength 200 */
  description: string;
  importance?: GoalImportance;
  /** @maxLength 5000 */
  justification?: string;
  bearings?: Bearing[];
  id?: string;
  userId?: string;
  user?: User;
  /** @maxLength 200 */
  name: string;
}
