/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GoalImportance } from './goalImportance';

export interface NorthStarGet {
  description?: string;
  importance?: GoalImportance;
  justification?: string;
  id?: string;
  name?: string;
}
