/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GoalImportance } from './goalImportance';
import type { GoalType } from './goalType';

export interface NorthStarCreate {
  description: string;
  importance: GoalImportance;
  justification?: string;
  name: string;
  type?: GoalType;
}
