/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GoalImportance } from './goalImportance';
import type { GoalType } from './goalType';

export interface NorthStarForm {
  description?: string;
  importance?: GoalImportance;
  justification?: string;
  name?: string;
  goalType?: GoalType;
}
