/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OnetimeEventCreate {
  /** @nullable */
  movementId?: string | null;
  /** @maxLength 200 */
  name: string;
  startDate: string;
  startTime: string;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  duration: string;
}
