/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OnetimeEventCreate {
  /** @nullable */
  movementId?: string | null;
  /** @maxLength 200 */
  name: string;
  start: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  duration: number | string;
}
