/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RecurrenceTypes } from './recurrenceTypes';
import type { Weekday } from './weekday';

export interface RecurringEventCreate {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  recurrenceAmount: number | string;
  recurrenceType: RecurrenceTypes;
  weekDays: Weekday[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  monthDay: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  yearMonth: number | string;
  /** @nullable */
  movementId: string | null;
  /** @maxLength 200 */
  name: string;
  start: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  duration: number | string;
}
