/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ReflectionGet {
  id: string;
  eventId?: string;
  positive?: string;
  negative?: string;
  improvement?: string;
}
