/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Goal } from './goal';

export interface User {
  accessCode: string;
  goals?: Goal[];
  /** @nullable */
  id?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  normalizedUserName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  normalizedEmail?: string | null;
  emailConfirmed?: boolean;
  /** @nullable */
  passwordHash?: string | null;
  /** @nullable */
  securityStamp?: string | null;
  /** @nullable */
  concurrencyStamp?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  twoFactorEnabled?: boolean;
  /** @nullable */
  lockoutEnd?: string | null;
  lockoutEnabled?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  accessFailedCount?: number | string;
}
