name: vite-deploy
on:
  workflow_dispatch:
jobs:
  validate:
    name: Vite Deploy
    runs-on: ubuntu-24.04 # AWS CLI preinstalled (see https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md)
    environment: production
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload assets
        run: aws s3 sync dist s3://$DO_SPACES_BUCKET --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          AWS_ENDPOINT_URL: https://fra1.digitaloceanspaces.com
